CREATE TABLE USER
(
	user_id NUMBER(19) PRIMARY KEY NOT NULL,
	name VARCHAR2(50) NOT NULL,
	password VARCHAR2(50) NOT NULL,
	active NUMBER(10),
);

CREATE TABLE ROLE
(
	role_id NUMBER(19) PRIMARY KEY NOT NULL,
	role VARCHAR2(50) NOT NULL,

);